apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
type: Opaque
stringData:
  connection-string: "Host=postgres;Database=inventory;Username=postgres;Password=changeme"
  api-key: "changeme"
